name: Dev Container Build and Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - 
      name: Checkout
      id: checkout
      uses: actions/checkout@v1
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - 
        name: Pre-build PHP dev container image
        uses: devcontainers/ci@v0.2
        with:
          subFolder: php
          imageName: ${{ env.REGISTRY }}/derroylo/devcontainer-prebuilds/php
          cacheFrom: ${{ env.REGISTRY }}/derroylo/devcontainer-prebuilds/php
          push: always