name: Dev Container Build and Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io

jobs:
  php-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - 
      name: Checkout
      id: checkout
      uses: actions/checkout@v1
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - 
        name: Pre-build PHP dev container image
        uses: devcontainers/ci@v0.2
        with:
          subFolder: php
          imageName: ${{ env.REGISTRY }}/derroylo/devcontainer-prebuilds/php
          cacheFrom: ${{ env.REGISTRY }}/derroylo/devcontainer-prebuilds/php
          push: always
  shopware-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - 
      name: Checkout
      id: checkout
      uses: actions/checkout@v1
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - 
        name: Pre-build Shopware dev container image
        uses: devcontainers/ci@v0.2
        with:
          subFolder: shopware
          imageName: ${{ env.REGISTRY }}/derroylo/devcontainer-prebuilds/shopware
          cacheFrom: ${{ env.REGISTRY }}/derroylo/devcontainer-prebuilds/shopware
          push: always
  symfony-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - 
      name: Checkout
      id: checkout
      uses: actions/checkout@v1
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - 
        name: Pre-build Symfony dev container image
        uses: devcontainers/ci@v0.2
        with:
          subFolder: symfony
          imageName: ${{ env.REGISTRY }}/derroylo/devcontainer-prebuilds/symfony
          cacheFrom: ${{ env.REGISTRY }}/derroylo/devcontainer-prebuilds/symfony
          push: always
  sulu-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - 
      name: Checkout
      id: checkout
      uses: actions/checkout@v1
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - 
        name: Pre-build Sulu dev container image
        uses: devcontainers/ci@v0.2
        with:
          subFolder: sulu
          imageName: ${{ env.REGISTRY }}/derroylo/devcontainer-prebuilds/sulu
          cacheFrom: ${{ env.REGISTRY }}/derroylo/devcontainer-prebuilds/sulu
          push: always
  oxid-1_10-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - 
      name: Checkout
      id: checkout
      uses: actions/checkout@v1
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - 
        name: Pre-build Oxid dev container image
        uses: devcontainers/ci@v0.2
        with:
          subFolder: oxid/1.10
          imageName: ${{ env.REGISTRY }}/derroylo/devcontainer-prebuilds/oxid-1_10
          cacheFrom: ${{ env.REGISTRY }}/derroylo/devcontainer-prebuilds/oxid-1_10
          push: always
  oxid-2_7-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - 
      name: Checkout
      id: checkout
      uses: actions/checkout@v1
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - 
        name: Pre-build Oxid dev container image
        uses: devcontainers/ci@v0.2
        with:
          subFolder: oxid/2.7
          imageName: ${{ env.REGISTRY }}/derroylo/devcontainer-prebuilds/oxid-2_7
          cacheFrom: ${{ env.REGISTRY }}/derroylo/devcontainer-prebuilds/oxid-2_7
          push: always
  oxid-2_2-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - 
      name: Checkout
      id: checkout
      uses: actions/checkout@v1
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - 
        name: Pre-build Oxid dev container image
        uses: devcontainers/ci@v0.2
        with:
          subFolder: oxid/2.2
          imageName: ${{ env.REGISTRY }}/derroylo/devcontainer-prebuilds/oxid-2_2
          cacheFrom: ${{ env.REGISTRY }}/derroylo/devcontainer-prebuilds/oxid-2_2
          push: always